"""Create users table in dev schema

Revision ID: 6012b2c60d4c
Revises: 
Create Date: 2025-06-18 11:18:30.301283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6012b2c60d4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('given_name', sa.String(), nullable=True),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_users_email'), 'users', ['email'], unique=True, schema='dev')
    op.create_index(op.f('ix_dev_users_google_id'), 'users', ['google_id'], unique=True, schema='dev')
    op.create_index(op.f('ix_dev_users_id'), 'users', ['id'], unique=False, schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dev_users_id'), table_name='users', schema='dev')
    op.drop_index(op.f('ix_dev_users_google_id'), table_name='users', schema='dev')
    op.drop_index(op.f('ix_dev_users_email'), table_name='users', schema='dev')
    op.drop_table('users', schema='dev')
    # ### end Alembic commands ###