"""Add documents table with string type

Revision ID: 92f3039a893c
Revises: 6012b2c60d4c
Create Date: 2025-06-18 13:25:48.940378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f3039a893c'
down_revision = '6012b2c60d4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['dev.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_documents_id'), 'documents', ['id'], unique=False, schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dev_documents_id'), table_name='documents', schema='dev')
    op.drop_table('documents', schema='dev')
    # ### end Alembic commands ###