"""Add structured analysis fields

Revision ID: e15f758835cd
Revises: e808ca395f32
Create Date: 2025-06-19 11:33:59.666511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15f758835cd'
down_revision = 'e808ca395f32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to existing document_analyses table
    op.add_column('document_analyses', sa.Column('role_fit_narrative', sa.Text(), nullable=True), schema='dev')
    op.add_column('document_analyses', sa.Column('strengths', sa.JSON(), nullable=True), schema='dev')
    op.add_column('document_analyses', sa.Column('gaps', sa.JSON(), nullable=True), schema='dev')
    return
    
    # The following was auto-generated but tables already exist
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('given_name', sa.String(), nullable=True),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_users_email'), 'users', ['email'], unique=True, schema='dev')
    op.create_index(op.f('ix_dev_users_google_id'), 'users', ['google_id'], unique=True, schema='dev')
    op.create_index(op.f('ix_dev_users_id'), 'users', ['id'], unique=False, schema='dev')
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['dev.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_documents_id'), 'documents', ['id'], unique=False, schema='dev')
    op.create_table('document_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_document_id', sa.Integer(), nullable=True),
    sa.Column('job_document_id', sa.Integer(), nullable=True),
    sa.Column('resume_analysis', sa.JSON(), nullable=True),
    sa.Column('job_analysis', sa.JSON(), nullable=True),
    sa.Column('connections_analysis', sa.JSON(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('role_fit_narrative', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_document_id'], ['dev.documents.id'], ),
    sa.ForeignKeyConstraint(['resume_document_id'], ['dev.documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dev.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_document_analyses_id'), 'document_analyses', ['id'], unique=False, schema='dev')
    op.create_table('ipp_stage_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('context_completed', sa.Boolean(), nullable=True),
    sa.Column('context_completed_at', sa.DateTime(), nullable=True),
    sa.Column('experience_completed', sa.Boolean(), nullable=True),
    sa.Column('experience_completed_at', sa.DateTime(), nullable=True),
    sa.Column('reflection_completed', sa.Boolean(), nullable=True),
    sa.Column('reflection_completed_at', sa.DateTime(), nullable=True),
    sa.Column('action_completed', sa.Boolean(), nullable=True),
    sa.Column('action_completed_at', sa.DateTime(), nullable=True),
    sa.Column('evaluation_completed', sa.Boolean(), nullable=True),
    sa.Column('evaluation_completed_at', sa.DateTime(), nullable=True),
    sa.Column('experience_data', sa.JSON(), nullable=True),
    sa.Column('reflection_data', sa.JSON(), nullable=True),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('evaluation_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['dev.document_analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dev.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_ipp_stage_progress_id'), 'ipp_stage_progress', ['id'], unique=False, schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the new columns
    op.drop_column('document_analyses', 'gaps', schema='dev')
    op.drop_column('document_analyses', 'strengths', schema='dev')
    op.drop_column('document_analyses', 'role_fit_narrative', schema='dev')
    # ### end Alembic commands ###