"""Add LLM analysis tables

Revision ID: e808ca395f32
Revises: 92f3039a893c
Create Date: 2025-06-18 13:55:32.247258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e808ca395f32'
down_revision = '92f3039a893c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_document_id', sa.Integer(), nullable=True),
    sa.Column('job_document_id', sa.Integer(), nullable=True),
    sa.Column('resume_analysis', sa.JSON(), nullable=True),
    sa.Column('job_analysis', sa.JSON(), nullable=True),
    sa.Column('connections_analysis', sa.JSON(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_document_id'], ['dev.documents.id'], ),
    sa.ForeignKeyConstraint(['resume_document_id'], ['dev.documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dev.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_document_analyses_id'), 'document_analyses', ['id'], unique=False, schema='dev')
    op.create_table('ipp_stage_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('context_completed', sa.Boolean(), nullable=True),
    sa.Column('context_completed_at', sa.DateTime(), nullable=True),
    sa.Column('experience_completed', sa.Boolean(), nullable=True),
    sa.Column('experience_completed_at', sa.DateTime(), nullable=True),
    sa.Column('reflection_completed', sa.Boolean(), nullable=True),
    sa.Column('reflection_completed_at', sa.DateTime(), nullable=True),
    sa.Column('action_completed', sa.Boolean(), nullable=True),
    sa.Column('action_completed_at', sa.DateTime(), nullable=True),
    sa.Column('evaluation_completed', sa.Boolean(), nullable=True),
    sa.Column('evaluation_completed_at', sa.DateTime(), nullable=True),
    sa.Column('experience_data', sa.JSON(), nullable=True),
    sa.Column('reflection_data', sa.JSON(), nullable=True),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('evaluation_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['dev.document_analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dev.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_ipp_stage_progress_id'), 'ipp_stage_progress', ['id'], unique=False, schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dev_ipp_stage_progress_id'), table_name='ipp_stage_progress', schema='dev')
    op.drop_table('ipp_stage_progress', schema='dev')
    op.drop_index(op.f('ix_dev_document_analyses_id'), table_name='document_analyses', schema='dev')
    op.drop_table('document_analyses', schema='dev')
    # ### end Alembic commands ###